### ISSUE TITLE
Reusing your code for Ruby HTM

### ISSUE THREAD

**Issue by ljulliar** [carver/pyHTM#2]
Jason (@carver),

I'm about tostart an implementation of the HTM CLA algorithms in Ruby and I'd like to start from your Python implementation. Is this OK with you ? Of course I will mention your name and project in the README file.

Laurent (@ljulliar)

**Comment by carver** [comment]
Absolutely!  Please note that I don't consider the project complete or correct to my satisfaction.  Also, since it's based off of something that Numenta (now Grok) posted a couple years ago and abandoned, the code may reference docs that don't exist anymore.

Either way, it was a fun exercise.  Enjoy...
